language: node_js
node_js: 14
install: skip
cache: yarn

jobs:
  include:
    - &build
      os: linux
      stage: build
      install: yarn
      script: yarn build
      # https://docs.travis-ci.com/user/using-workspaces/
      workspaces:
        create:
          name: linux-shared
          paths:
            - node_modules
            - target
            - flow-typed
            - typings
            - docs
    - <<: *build
      os: windows
      # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
      env: YARN_GPG=no
      workspaces:
        create:
          name: win-shared
          paths:
            - node_modules
            - target

    - &test
      stage: test
      os: linux
      node_js: 12
      script: yarn test
      workspaces:
        use: linux-shared
    - <<: *test
      os: windows
      env: YARN_GPG=no
      node_js:
        - 12
        - 14
      workspaces:
        use: win-shared
    - <<: *test
      node_js: 14
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn test:report
      after_script:
        - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: release
      if: branch = master AND type != pull_request
      workspaces:
        use: linux-shared
      script: echo 'Deploy step is disabled' && exit 0
      # script: npx -p @qiwi/semrel-toolkit multi-semrel
